export default {
  products: [
    {
      _id: 1,
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: 2,
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d2.jpg",
      price: 50,
      brand: "Adidas",
      rating: 4.3,
      numReviews: 5,
    },
    {
      _id: 3,
      name: "Regular Shirt",
      category: "Shirts",
      image: "/images/d3.jpg",
      price: 55,
      brand: "Reserved",
      rating: 4.3,
      numReviews: 10,
    },
    {
      _id: 4,
      name: "Fit Pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: 5,
      name: "Slim Pants",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 60,
      brand: "Tommy",
      rating: 3.9,
      numReviews: 8,
    },
    {
      _id: 6,
      name: "Regular Pants",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 60,
      brand: "Tommy",
      rating: 3.9,
      numReviews: 8,
    },
  ],
};
